# Generated by Django 4.0.3 on 2022-07-22 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
