# Generated by Django 4.0.3 on 2022-07-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_uploadimage_uploadimageachieve'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimageachieve',
            name='image',
            field=models.ImageField(upload_to='achieveimages'),
        ),
    ]
