# Generated by Django 4.0.3 on 2022-07-23 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_uploadimageart_uploadimagedance_uploadimageevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadImageStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='studioimages')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
