# Generated by Django 4.0.6 on 2022-07-27 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_uploadimagestudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimageachieve',
            name='caption',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimageart',
            name='caption',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimagedance',
            name='caption',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimageevent',
            name='caption',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='uploadimagestudio',
            name='caption',
            field=models.TextField(default=None, null=True),
        ),
    ]
